// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AsyncMethodNameFixer.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "3f1bd9bf-d048-4430-8705-1a26a4819614";
        public const string Name = "Async Method Name Fixer";
        public const string Description = @"The easiest way to analyze and fix method names for asynchronous methods.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Priyanshu Agrawal";
        public const string Tags = "analyzer, async, asynchronous, C#, code analysis, name fix, refactoring, roslyn";
    }
}
